/* Standalone chart demo: no folder or CSV import is required. */
data chart_sample;
  length category $ 6;
  do id = 1 to 120;
    x = id;
    y = sqrt(id) + mod(id, 7);
    amount = 10 + mod(id, 17);
    if mod(id, 3) = 0 then category = 'Alpha';
    else if mod(id, 3) = 1 then category = 'Beta';
    else category = 'Gamma';
    output;
  end;
run;
title 'Values by category';
proc sgplot data=chart_sample;
  scatter x=x y=y / group=category;
  xaxis label='Observation';
  yaxis label='Calculated value';
run;
title 'Total amount by category';
proc sgplot data=chart_sample;
  hbar category / response=amount stat=sum;
run;
title 'Mean amount by category';
proc sgplot data=chart_sample;
  vbar category / response=amount stat=mean;
run;
title 'Distribution of calculated values';
proc sgplot data=chart_sample;
  histogram y / nbins=12 scale=count;
run;
title 'Share of total amount';
proc sgpie data=chart_sample;
  pie category / response=amount stat=sum;
run;
title;
