import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {runFileProgram} from './dist/file-program.mjs';
import {parseCSV} from './dist/engine.mjs';
import {writeTable,readTable} from './dist/table-storage.mjs';
import {programExamples} from './dist/example-programs.mjs';
const ds=parseCSV('site,period,x,y\nA,1,1,10\nA,2,3,\nB,1,5,30\nB,2,,50\n,1,100,100');
const run=code=>runFileProgram(code,{input:ds});
let r=await run('proc means data=input n nmiss mean std var; class site period; var x y; output out=stats n= nmiss= mean= std= var= / autoname; run;');
const rows=r.datasets.stats.rows;
assert.deepEqual(rows.map(x=>x._type_),[0,1,1,2,2,3,3,3,3]);
assert.deepEqual(rows[0],{site:'',period:null,_type_:0,_freq_:4,x_n:3,y_n:3,x_nmiss:1,y_nmiss:1,x_mean:3,y_mean:30,x_std:2,y_std:20,x_var:4,y_var:400});
assert.equal(rows[1].site,'');assert.equal(rows[1].period,1);assert.equal(rows[1].x_var,8);
assert.equal(rows[3].site,'A');assert.equal(rows[3].period,null);assert.equal(rows[3].x_mean,2);
assert.equal(r.reports[0].dataset.rows.length,8);assert.ok(r.reports[0].dataset.rows.every(row=>row.site!==''&&row.period!==null));
assert.deepEqual(readTable(writeTable(r.datasets.stats,'stats')).rows,rows);
r=await run('proc means data=input nway noprint; class site period; var x; output out=stats mean=avg; run;');assert.ok(r.datasets.stats.rows.every(row=>row._type_===3));assert.equal(r.reports.length,0);
r=await run('proc means data=input missing; class site period; var x; output out=stats n=n; run;');assert.equal(r.datasets.stats.rows[0]._freq_,5);assert.equal(r.datasets.stats.rows[0].n,4);
r=await run('proc means data=input noprint; var x; output out=stats; run;');assert.deepEqual(r.datasets.stats.rows.map(row=>row._stat_),['N','MIN','MAX','MEAN','STD']);assert.equal(r.datasets.stats.rows[0]._freq_,5);assert.equal(r.datasets.stats.rows[0].x,4);
r=await runFileProgram('data input; do x=1 to 10; output; end; run; proc means data=input; var x; output out=stats n=count mean=avg std=sd var=variance stderr=se css=css uss=uss sum=sum range=span cv=cv; run;');
const s=r.datasets.stats.rows[0];assert.equal(s.count,10);assert.equal(s.avg,5.5);assert.equal(s.variance,55/6);assert.equal(s.css,82.5);assert.equal(s.uss,385);assert.equal(s.sum,55);assert.equal(s.span,9);assert.ok(Math.abs(s.sd-3.0276503540974917)<1e-15);
r=await runFileProgram('data input; do i=0 to 2; x=1000000000000+i; output; end; run; proc means data=input vardef=n; var x; output out=stats var=v mean=m; run;');assert.equal(r.datasets.stats.rows[0].v,2/3);assert.equal(r.datasets.stats.rows[0].m,1000000000001);
r=await runFileProgram('data input; x=5; output; x=.; output; run; proc means data=input; var x; output out=stats n=n nmiss=nm var=v std=s; run;');assert.deepEqual(r.datasets.stats.rows[0],{_type_:0,_freq_:2,n:1,nm:1,v:null,s:null});
r=await runFileProgram('data input; x=.; output; run; proc means data=input; var x; output out=stats n=n nmiss=nm mean=m sum=s; run;');assert.equal(r.datasets.stats.rows[0].n,0);assert.equal(r.datasets.stats.rows[0].nm,1);assert.equal(r.datasets.stats.rows[0].m,null);assert.equal(r.datasets.stats.rows[0].s,0);
r=await runFileProgram("data input; g=1.1; x=2; output; g=1.2; x=4; output; format g 2.0; run; proc means data=input; class g; var x; output out=stats mean=m; run;");assert.equal(r.datasets.stats.rows.length,2);assert.equal(r.datasets.stats.rows[1].g,1.1);assert.equal(r.datasets.stats.rows[1].m,3);
r=await runFileProgram("data input; g=1.1; h=1; x=2; output; g=1.2; h=2; x=4; output; format g 2.0; run; proc means data=input nway; class g h; var x; output out=stats mean=m; run;");assert.ok(r.datasets.stats.rows.every(row=>row.g===1.1));
r=await run('proc sort data=input out=sorted; by site; run; proc means data=sorted; by site; var x; output out=stats mean=m; run;');assert.equal(r.datasets.stats.rows.length,3);assert.equal(r.datasets.stats.rows[0].site,'');
await assert.rejects(run('proc means data=input; by site; var x; run;'),/not sorted/);
for(const option of ['weight x;','freq x;','types site;','ways 1;'])await assert.rejects(run('proc means data=input; '+option+' run;'),/Unsupported/);
await assert.rejects(run('proc means data=input median; run;'),/Unsupported/);
await assert.rejects(run('proc means data=input vardef=n stderr; run;'),/STDERR/);
await assert.rejects(run('proc means data=input; var site; run;'),/numeric/);
await assert.rejects(run('proc means data=input; var x; output out=stats mean=x std=x; run;'),/Conflicting/);
r=await run('proc means data=input; var x y; output out=stats mean(x)=selected n(y)=count / autoname; run;');assert.ok(r.datasets.stats.columns.includes('selected'));assert.ok(!r.datasets.stats.columns.includes('selected_mean'));
const permanent=await runFileProgram("libname saved 'tables'; proc means data=input; class site period; var x; output out=saved.stats mean=m; run; data loaded; set saved.stats; run;",{input:ds},async()=>{throw new Error('Unexpected disk read')},{checkDirectory:async()=>true});assert.equal(permanent.exports.length,1);assert.deepEqual(permanent.datasets.loaded.rows,permanent.datasets['saved.stats'].rows);
for(const example of programExamples())if(!['06-project-csv.sas','07-json-libraries.sas'].includes(example.file)){const result=await runFileProgram(example.code);assert.ok(result.written.length,example.file);assert.equal(example.code,await readFile('examples/catalog/'+example.file,'utf8'));}
r=await runFileProgram("data input; variable='A'; x=1; run; proc means data=input noprint; class variable; var x; output out=stats mean=m; run;");assert.equal(r.datasets.stats.rows.length,2);
console.log('PROC MEANS totals/type bits/frequencies/default rows, per-variable missingness, moments, formatted CLASS, BY, NWAY, native storage and example programs passed.');
