import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {runFileProgram,filePlan} from './dist/file-program.mjs';
import {readTable,writeTable} from './dist/table-storage.mjs';
import {parseCSV,run} from './dist/engine.mjs';
const data=parseCSV('category,group,x,y,amount\nB,one,1,2,10\nA,two,2,4,20\nB,one,3,6,30\nA,one,4,8,40\nB,two,,,50\n,one,5,10,60');
const runPlot=code=>runFileProgram(code,{test:data});
let result=await runPlot("title 'Demo';proc sgplot data=work.test;scatter x=x y=y / group=group;xaxis label='Input';yaxis label='Result';run;");
let chart=result.plots[0];assert.equal(chart.title,'Demo');assert.equal(chart.xLabel,'Input');assert.equal(chart.yLabel,'Result');assert.equal(chart.used,5);assert.equal(chart.omitted,1);assert.deepEqual(chart.series.map(s=>s.data.length),[4,1]);
assert.deepEqual(chart.series[0].data[0],{x:1,y:2});assert.equal(result.chartTitle,'Demo');
result=await runPlot('proc sgplot data=test;vbar category / response=amount stat=sum;run;');chart=result.plots[0];assert.deepEqual(chart.labels,['B','A']);assert.deepEqual(chart.series[0].data,[90,60]);assert.equal(chart.omitted,1);
result=await runPlot('proc sgplot data=test;hbar category / response=amount stat=mean group=group groupdisplay=cluster;run;');chart=result.plots[0];assert.deepEqual(chart.series.map(s=>s.data),[[20,40],[50,20]]);assert.equal(chart.stacked,false);assert.equal(chart.xLabel,'MEAN(amount)');
result=await runPlot('proc sgplot data=test;vbar category / group=group;run;');assert.deepEqual(result.plots[0].series.map(s=>s.data),[[2,1],[1,1]]);assert.equal(result.plots[0].stacked,true);
result=await runPlot('proc sgpie data=test;pie category / response=amount stat=sum;run;');assert.deepEqual(result.plots[0].series[0].data,[90,60]);
result=await runPlot('proc sgplot data=test;histogram x / nbins=2 scale=count;run;');chart=result.plots[0];assert.deepEqual(chart.binCounts,[2,3]);assert.deepEqual(chart.binEdges,[1,3,5]);assert.equal(chart.used,5);assert.equal(chart.omitted,1);
result=await runPlot('proc sgplot data=test;histogram x / nbins=2;run;');assert.deepEqual(result.plots[0].series[0].data,[40,60]);
result=await runPlot('proc sgplot data=test;histogram x / nbins=2 scale=proportion;run;');assert.deepEqual(result.plots[0].series[0].data,[.4,.6]);
result=await runFileProgram('data constant;do i=1 to 3;x=7;output;end;run;proc sgplot data=constant;histogram x / nbins=10 scale=count;run;');assert.deepEqual(result.plots[0].binCounts,[3]);
// Chart snapshots are captured at the procedure's position, before later replacement.
result=await runFileProgram('data values;x=1;y=2;run;proc sgplot data=values;scatter x=x y=y;run;data values;x=9;y=10;run;proc sgplot data=values;scatter x=x y=y;run;');assert.equal(result.plots[0].series[0].data[0].x,1);assert.equal(result.plots[1].series[0].data[0].x,9);
result=await runFileProgram('title;proc sgplot data=test;vbar category;run;', {test:data},undefined,{chartTitle:'Old'});assert.equal(result.chartTitle,'');assert.ok(result.plots[0].title.startsWith('Vertical'));
result=await runFileProgram("%let which=x;title 'Macro plot';proc sgplot data=test;scatter x=&which y=y;run;",{test:data});assert.equal(result.plots[0].used,5);
const native=writeTable(data,'test');const reads=[];result=await runFileProgram("libname saved 'tables';proc sgplot data=saved.test;histogram x / nbins=2 scale=count;run;",{},async path=>{reads.push(path);return native},{checkDirectory:async()=>true});assert.deepEqual(reads,['tables/test.sassy-table.json']);assert.deepEqual(result.plots[0].binCounts,[2,3]);
for(const code of ['proc sgplot data=test;scatter x=x;run;','proc sgplot data=test;vbar category / stat=median;run;','proc sgplot data=test;histogram x / nbins=0;run;','proc sgplot data=test;scatter x=x y=y;vbar category;run;','proc sgpie data=test;pie category / group=group;run;','proc sgplot data=test;histogram x / binwidth=10;run;','proc sgplot data=test;vbar category / stat=mean;run;','title1 "Not supported";'])assert.throws(()=>filePlan(code));
for(const code of ['proc sgplot data=unknown;vbar category;run;','proc sgplot data=test;scatter x=category y=y;run;','proc sgplot data=test;histogram absent;run;'])await assert.rejects(runPlot(code));
await assert.rejects(runFileProgram('data bad;x=.;run;proc sgplot data=bad;histogram x;run;'),/No valid/);
await assert.rejects(runFileProgram('data bad;length c $ 1;c="a";x=-1;run;proc sgpie data=bad;pie c / response=x;run;'),/nonnegative/);
await assert.rejects(runFileProgram('data lots;do i=1 to 20001;x=i;y=i;output;end;run;proc sgplot data=lots;scatter x=x y=y;run;'),/20,000/);
await assert.rejects(runFileProgram('data many;do c=1 to 201;output;end;run;proc sgplot data=many;vbar c;run;'),/200 categories/);
await assert.rejects(runFileProgram('proc sgplot data=test;vbar category;run;'.repeat(21),{test:data}),/20 charts/);
await assert.rejects(runFileProgram("data pending;x=1;run;proc export data=pending outfile='no.csv' dbms=csv replace;run;proc sgplot data=pending;scatter x=x y=absent;run;"),/not found/);
assert.deepEqual(await runFileProgram('data ordinary;x=1;run;'),run('data ordinary;x=1;run;'));
assert.deepEqual(await runFileProgram('data ordinary;title=1;libname=2;keep title libname;run;'),run('data ordinary;title=1;libname=2;keep title libname;run;'));
assert.equal(readTable(native).rows.length,6);
const demo=await runFileProgram(await readFile('examples/project-demo/charts-demo.sas','utf8'));assert.equal(demo.plots.length,5);
console.log('Chart checks passed: scatter/groups, sum/mean/frequency bars, pie, histogram counts/boundaries/scales, missing data, titles/macros, native libraries, snapshots, bounds and failed-run rollback.');
