/* Run unchanged in Sassy or SAS. Deterministic inputs isolate PROC MEANS.
   Includes missing analysis values, missing CLASS values, all CLASS types,
   NWAY, five-row default OUTPUT, sorted BY, and large-offset variance. */
data means_inputs;
    length site $ 8;
    do id=1 to 48;
        if mod(id,2)=0 then site='North'; else site='South';
        period=mod(id,3)+1;
        amount=100+id*7;
        other=id**2;
        if mod(id,5)=0 then amount=.;
        if mod(id,7)=0 then other=.;
        if id=48 then site='';
        output;
    end;
run;
proc means data=means_inputs n nmiss mean std var min max;
    class site period;
    var amount other;
    output out=means_all n= nmiss= mean= std= var= min= max= / autoname;
run;
proc means data=means_inputs missing noprint;
    class site period;
    var amount;
    output out=means_missing n=count nmiss=missing_count mean=avg;
run;
proc means data=means_inputs nway noprint;
    class site period;
    var amount;
    output out=means_nway n=count mean=avg;
run;
proc means data=means_inputs noprint;
    var amount other;
    output out=means_default;
run;
proc sort data=means_inputs out=means_sorted;
    by site;
run;
proc means data=means_sorted noprint;
    by site;
    var amount;
    output out=means_by n=count mean=avg var=variance;
run;
data means_large_inputs;
    do id=0 to 20;
        value=1000000000000+id;
        output;
    end;
run;
proc means data=means_large_inputs noprint;
    var value;
    output out=means_large n=count mean=avg var=variance std=sd css=css;
run;
